# Generated by Django 5.0 on 2023-12-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_remove_album_artista_remove_musica_album_todo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nome',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userneme',
        ),
    ]
